services:
  backend:
    build:
      context: backend
    ports:
      - 8080:8080
    environment:
      DATABASE_HOST: db
      DATABASE_USER: root
      CHROMA_HOST: chromadb
      MYSQL_ROOT_PASSWORD: matiasGASTONsantiago
      MYSQL_DATABASE: diagnostico
    networks:
      - private
      - public
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - private
    volumes:
      - ./mysql:/mysql/mysql
    environment:
      MYSQL_ROOT_PASSWORD: matiasGASTONsantiago
      MYSQL_DATABASE: diagnostico
    ports:
      - "3306:3306"
  chromadb:
    image: chromadb/chroma:latest
    volumes:
      - ./chromadb:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma # this is the default path, change it as needed
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY:-TRUE}
    ports:
      - 8000:8000
    networks:
      - private
  frontend:
    build:
      context: frontend
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - public
networks:
  public:
  private:
    driver: bridge
volumes:
  db-data: