-- MySQL Script generated by MySQL Workbench
-- Wed May  1 23:07:26 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema diagnostico
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema diagnostico
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `diagnostico` DEFAULT CHARACTER SET utf8 ;
USE `diagnostico` ;

-- -----------------------------------------------------
-- Table `diagnostico`.`Provinces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diagnostico`.`Provinces` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diagnostico`.`Departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diagnostico`.`Departments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `idProvince` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `prov_id_idx` (`idProvince` ASC),
  CONSTRAINT `prov_id`
    FOREIGN KEY (`idProvince`)
    REFERENCES `diagnostico`.`Provinces` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diagnostico`.`Municipalities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diagnostico`.`Municipalities` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idDepartment` INT UNSIGNED NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `dpto_id_idx` (`idDepartment` ASC),
  CONSTRAINT `dpto_id`
    FOREIGN KEY (`idDepartment`)
    REFERENCES `diagnostico`.`Departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diagnostico`.`Localities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diagnostico`.`Localities` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idMunicipality` INT UNSIGNED NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `latitud` VARCHAR(45) NOT NULL,
  `longitud` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `muni_id_idx` (`idMunicipality` ASC),
  CONSTRAINT `muni_id`
    FOREIGN KEY (`idMunicipality`)
    REFERENCES `diagnostico`.`Municipalities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
